services:
  chatdragon-instant-vllm:
    image: vllm/vllm-openai:v0.20.1
    container_name: chatdragon-instant-vllm
    ipc: host
    ports:
      - "10046:10046"
    volumes:
      - /PATH/TO/CKPT:/model:ro
    command:
      - --model
      - /model
      - --tensor_parallel_size=4
      - --port
      - "10046"
      - --reasoning-parser
      - qwen3
      - --served-model-name
      - ChatDRAGON-Instant
      - --max-model-len
      - "12000"
      - --max-num-seqs
      - "32"
      - --enable-auto-tool-choice
      - --tool-call-parser
      - qwen3_coder
      - --enable-prefix-caching
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["2", "3", "4", "5"]
              capabilities: [gpu]
    restart: unless-stopped
