#!/usr/bin/env python3
"""Render every generated config file from ``models.yaml``.

``models.yaml`` is the single place a model's facts live. This script turns it
into the files the running system actually reads, so those can never be edited
into disagreeing with each other:

  litellm_config.yaml     one LiteLLM entry per name a client may send
                          (canonical id + every alias), identical params
  compose/<id>.yml        a compose profile per model whose ``serve.engine`` this
                          repo launches (vllm, llamacpp); ``external`` = only a
                          port is known, nothing to launch
  .env.rendered           env the sanitizer reads: SANITIZER_EFFORT_VOCABULARY,
                          a JSON map with every alias expanded

Usage:
  python3 scripts/render.py            # write the files
  python3 scripts/render.py --check    # exit 1 if any committed file drifted
  MODELS_FILE=models.local.yaml python3 scripts/render.py
                                       # a deployment's private registry (gitignored)

Only PyYAML is required; the LiteLLM image already ships it.
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
ENGINES_WE_LAUNCH = ("vllm", "llamacpp")
CONTAINER_PORT = {"vllm": 8000, "llamacpp": 8080}
ROLES = ("gateway", "direct")


class RegistryError(ValueError):
    """``models.yaml`` does not describe a consistent set of models."""


# --------------------------------------------------------------------------- #
# Registry
# --------------------------------------------------------------------------- #


def load_registry(path: Path) -> dict:
    data = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    models = data.get("models")
    if not isinstance(models, list) or not models:
        raise RegistryError(f"{path}: 'models' must be a non-empty list")
    seen: dict[str, str] = {}
    for m in models:
        for key in ("id", "roles", "serve", "litellm"):
            if key not in m:
                raise RegistryError(f"model {m.get('id', '?')!r} is missing {key!r}")
        for name in every_name(m):
            if name in seen:
                raise RegistryError(
                    f"name {name!r} is declared by both {seen[name]!r} and {m['id']!r}; "
                    "one client-facing name must route to exactly one backend"
                )
            seen[name] = m["id"]
        bad = [r for r in m["roles"] if r not in ROLES]
        if bad:
            raise RegistryError(f"model {m['id']!r} has unknown role(s) {bad}; known: {ROLES}")
        engine = m["serve"].get("engine")
        if engine not in ENGINES_WE_LAUNCH + ("external",):
            raise RegistryError(f"model {m['id']!r}: unknown serve.engine {engine!r}")
        if "port" not in m["serve"]:
            raise RegistryError(f"model {m['id']!r}: serve.port is required")
        if "provider" not in m["litellm"]:
            raise RegistryError(f"model {m['id']!r}: litellm.provider is required")
    return data


def every_name(model: dict) -> list[str]:
    """The canonical id first, then every alias — the order entries are emitted."""
    return [model["id"], *model.get("aliases", [])]


# --------------------------------------------------------------------------- #
# litellm_config.yaml
# --------------------------------------------------------------------------- #


def render_litellm(reg: dict) -> str:
    defaults = (reg.get("defaults") or {}).get("litellm", {})
    entries = []
    for m in reg["models"]:
        serve, lit = m["serve"], m["litellm"]
        host = serve.get("host", "localhost")
        params = {
            # LiteLLM routes on the provider-prefixed *canonical* id; every alias
            # is just another public name for the same backend.
            "model": f"{lit['provider']}/{m['id']}",
            "api_base": f"http://{host}:{serve['port']}/v1",
            "api_key": lit.get("api_key", defaults.get("api_key", "EMPTY")),
            "max_tokens": lit["max_tokens"],
        }
        if lit.get("merge_reasoning_content_in_choices"):
            params["merge_reasoning_content_in_choices"] = True
        for name in every_name(m):
            entries.append({"model_name": name, "litellm_params": dict(params)})

    doc = {
        "model_list": entries,
        "litellm_settings": {"ssl_verify": False, "set_verbose": True, "drop_params": True},
        # The master key comes from the environment, never from a committed file.
        "general_settings": {"master_key": "os.environ/LITELLM_MASTER_KEY"},
    }
    header = (
        "# GENERATED by scripts/render.py from models.yaml — do not edit by hand.\n"
        "# Add or change a model in models.yaml and run `python3 scripts/render.py`.\n"
    )
    return header + yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=100)


# --------------------------------------------------------------------------- #
# compose profiles
# --------------------------------------------------------------------------- #


def _cli_args(args: dict) -> list[str]:
    """``{flag: value|None}`` → ``["--flag", "value", "--switch"]`` in declared order."""
    out: list[str] = []
    for flag, value in (args or {}).items():
        out.append(f"--{flag}")
        if value is not None:
            out.append(str(value))
    return out


def _shell_quote(arg: str) -> str:
    """Quote one argument for the ``sh -c`` command string (no `$` inside)."""
    return arg if arg.replace("-", "").replace(".", "").isalnum() else "'" + arg.replace("'", "'\\''") + "'"


def _gpu_reservation(gpus) -> dict:
    device: dict = {"driver": "nvidia", "capabilities": ["gpu"]}
    if gpus == "all" or gpus is None:
        device["count"] = "all"
    else:
        device["device_ids"] = [str(g) for g in gpus]
    return {"resources": {"reservations": {"devices": [device]}}}


def render_compose(model: dict) -> str | None:
    serve = model["serve"]
    engine = serve["engine"]
    if engine not in ENGINES_WE_LAUNCH:
        return None
    name = f"{model['id']}-{engine}"
    service: dict = {
        "image": serve["image"],
        "container_name": name,
        "profiles": [model["id"]],
        "ports": [f"{serve['port']}:{CONTAINER_PORT[engine]}"],
        "restart": "unless-stopped",
        "deploy": _gpu_reservation(serve.get("gpus")),
    }
    if serve.get("environment"):
        service["environment"] = dict(serve["environment"])

    if engine == "vllm":
        service["ipc"] = "host"
        service["volumes"] = [f"{serve['checkpoint']}:/model:ro"]
        service["command"] = [
            "--model", "/model",
            "--served-model-name", model["id"],
            *_cli_args(serve.get("args")),
            "--api-key", "EMPTY",
        ]
    else:  # llamacpp
        service["volumes"] = [f"{serve['checkpoint']}:/models:ro"]
        gguf = serve.get("gguf") or ""
        server_args = [
            "--host", "0.0.0.0",
            "--port", str(CONTAINER_PORT[engine]),
            *_cli_args(serve.get("args")),
        ]
        if gguf:
            # The image's entrypoint is the server; pass arguments directly.
            service["command"] = ["-m", f"/models/{gguf}", *server_args]
        else:
            # No file named: pick the first *.gguf at start time, as the old
            # launcher did. That needs a shell, so the command is one string;
            # `$$` is compose's escape for a literal `$`.
            service["entrypoint"] = ["/bin/sh", "-c"]
            quoted = " ".join(_shell_quote(a) for a in server_args)
            service["command"] = [
                'exec /app/llama-server -m "$$(ls /models/*.gguf | head -n 1)" ' + quoted
            ]
        service["healthcheck"] = {
            "test": ["CMD-SHELL", f"curl -f http://localhost:{CONTAINER_PORT[engine]}/health || exit 1"],
            "interval": "30s", "timeout": "10s", "retries": 5, "start_period": "120s",
        }

    header = (
        f"# GENERATED by scripts/render.py from models.yaml ({model['id']}) — do not edit by hand.\n"
        f"# Start with: docker compose --profile {model['id']} up -d\n"
    )
    return header + yaml.safe_dump({"services": {name: service}}, sort_keys=False, width=100)


# --------------------------------------------------------------------------- #
# .env.rendered
# --------------------------------------------------------------------------- #


def render_env(reg: dict) -> str:
    vocab: dict[str, str] = {}
    for m in reg["models"]:
        levels = (m.get("sanitizer") or {}).get("effort_supported")
        if levels:
            for name in every_name(m):
                vocab[name] = ",".join(levels)
    lines = [
        "# GENERATED by scripts/render.py from models.yaml — do not edit by hand.",
        "# Source this (or merge into .env). Values the sanitizer/LiteLLM read.",
    ]
    if vocab:
        lines.append(f"SANITIZER_EFFORT_VOCABULARY={json.dumps(vocab, separators=(',', ':'))}")
    else:
        lines.append("# SANITIZER_EFFORT_VOCABULARY=  (no model declares sanitizer.effort_supported)")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# driver
# --------------------------------------------------------------------------- #


def render_all(reg: dict) -> dict[Path, str]:
    out = {ROOT / "litellm_config.yaml": render_litellm(reg), ROOT / ".env.rendered": render_env(reg)}
    for m in reg["models"]:
        text = render_compose(m)
        if text is not None:
            out[ROOT / "compose" / f"{m['id']}.yml"] = text
    return out


def include_problems(files: dict[Path, str], compose_file: Path = ROOT / "docker-compose.yml") -> list[str]:
    """Why ``docker-compose.yml``'s ``include:`` disagrees with the rendered profiles.

    The include list is the one hand-maintained line per launched model, so it is
    the one place a new model can be rendered and still never start. Every
    rendered ``compose/<id>.yml`` must be included, and every included path must
    be one that is rendered (a stale entry makes ``docker compose`` refuse to
    start at all).
    """
    if not compose_file.exists():
        return [f"{compose_file.name} is missing"]
    doc = yaml.safe_load(compose_file.read_text(encoding="utf-8")) or {}
    included = set()
    for entry in doc.get("include") or []:
        path = entry.get("path") if isinstance(entry, dict) else entry
        if isinstance(path, str):
            included.add(path)
    rendered = {str(p.relative_to(ROOT)) for p in files if p.parent == ROOT / "compose"}
    problems = [f"compose/{Path(p).name} is rendered but not in {compose_file.name} include:" for p in sorted(rendered - included)]
    problems += [f"{p} is in {compose_file.name} include: but models.yaml renders no such profile" for p in sorted(included - rendered)]
    return problems


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if any rendered file differs from disk")
    ns = ap.parse_args(argv)

    models_file = Path(os.environ.get("MODELS_FILE", ROOT / "models.yaml"))
    try:
        reg = load_registry(models_file)
        files = render_all(reg)
    except (RegistryError, yaml.YAMLError, KeyError) as exc:
        print(f"render: {exc}", file=sys.stderr)
        return 2

    drifted = []
    for path, text in files.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == text:
            continue
        drifted.append(path)
        if not ns.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")

    problems = include_problems(files)
    for problem in problems:
        print(f"INCLUDE: {problem}", file=sys.stderr)

    if ns.check:
        if problems:
            return 1
        if drifted:
            for p in drifted:
                print(f"DRIFT: {p.relative_to(ROOT)} does not match models.yaml", file=sys.stderr)
            print("run `python3 scripts/render.py` and commit the result", file=sys.stderr)
            return 1
        print(f"ok: {len(files)} rendered file(s) match models.yaml")
    elif not drifted:
        print("nothing to do: all rendered files already match models.yaml")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
